services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo stat | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - app-network


  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d rules_db" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network


  adminPanel:
    container_name: Admin_Panel
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network


  redis:
    image: redis:5.0.3-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network


  mongodb:
    image: mongo:4.0.10
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network


  java-service-filtering:
    image: yabrazhkin/filtering-service:1.0
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      DB_JDBC_URL: ${DB_JDBC_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}

      KAFKA_CONSUMER_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_CONSUMER_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      KAFKA_CONSUMER_TOPICS: ${KAFKA_CONSUMER_TOPICS_FILTERING}

      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_PRODUCER_TOPIC: ${KAFKA_PRODUCER_TOPIC_FILTERING}

      APPLICATION_UPDATE_INTERVAL_SEC: ${APPLICATION_UPDATE_INTERVAL_SEC}
      SERVER_PORT: ${FILTERING_SERVER_PORT}

    networks:
      - app-network


  java-service-deduplication:
    image: yabrazhkin/deduplication-service:1.0
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_healthy

    environment:
      DB_JDBC_URL: ${DB_JDBC_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}

      KAFKA_CONSUMER_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_CONSUMER_GROUP_ID: "group_consumer"
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"
      KAFKA_CONSUMER_TOPICS: ${KAFKA_CONSUMER_TOPICS_DEDUPLICATION}

      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_PRODUCER_TOPIC: ${KAFKA_PRODUCER_TOPIC_DEDUPLICATION}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      APPLICATION_UPDATE_INTERVAL_SEC: ${APPLICATION_UPDATE_INTERVAL_SEC}
      SERVER_PORT: ${DEDUPLICATION_SERVER_PORT}

    networks:
      - app-network


  java-service-enrichment:
    image: yabrazhkin/enrichment-service:1.0
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      mongodb:
        condition: service_healthy
    environment:
      DB_JDBC_URL: ${DB_JDBC_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DRIVER: ${DB_DRIVER}

      KAFKA_CONSUMER_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_CONSUMER_GROUP_ID: "group_consumer"
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"
      KAFKA_CONSUMER_TOPICS: ${KAFKA_CONSUMER_TOPICS_ENRICHMENT}

      KAFKA_PRODUCER_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_PRODUCER_TOPIC: ${KAFKA_PRODUCER_TOPIC_ENRICHMENT}

      MONGO_CONNECTION_STRING: "mongodb://admin:admin@mongodb:27017"
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_COLLECTION: ${MONGO_COLLECTION}

      APPLICATION_ENRICHMENT_ID: "1"
      APPLICATION_UPDATE_INTERVAL_SEC: ${APPLICATION_UPDATE_INTERVAL_SEC}
      SERVER_PORT: ${ENRICHMENT_SERVER_PORT}
    networks:
      - app-network


  java-service-management:
    image: yabrazhkin/management-service:1.0
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE: postgresql
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      SERVER_PORT: ${MANAGEMENT_SERVER_PORT}

      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ACCESS: "read_only"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      MANAGEMENT_INFO_METRICS_ENABLED: "true"
    networks:
      - app-network

  java-bff-service:
    image: yabrazhkin/bff-service:1.0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      java-service-management:
        condition: service_started
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DRIVER: jdbc:postgresql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      MANAGEMENT_HTTP_PROTOCOL: http
      MANAGEMENT_HOST: java-service-management
      MANAGEMENT_PORT: 8081
      DEDUPLICATION_BASE_PATH: deduplication
      ENRICHMENT_BASE_PATH: enrichment
      FILTER_BASE_PATH: filter

      APPLICATION_PORT: ${BFF_SERVER_PORT}

      SPRING_PROFILES_ACTIVE: prod
      SPRING_LIQUIBASE_ENABLED: "true"

      TOPIC_IN: ${BFF_TOPIC_IN}
      TOPIC_OUT: ${BFF_TOPIC_OUT}
    ports:
      - "8080:8084"
    networks:
      - app-network


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - java-bff-service
      - java-service-management
      - java-service-filtering
      - java-service-deduplication
      - java-service-enrichment
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  pg_data:
  redis_data:
  mongodb_data:
  grafana_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge


